React version
mendix/ClipboardTextCopy pull request #4
Opened 2019-09-11 07:45 UTC by MeisamMahdian

- React version
- Support of usage in list view
- New "button class" property

2019-09-12 08:32 UTC, iannbing commented on src/index.tsx
> +  update(contextObject: mendix.lib.MxObject, callback: () => void) {
`contextObject` is not used? Consider removing it?

2019-09-12 08:34 UTC, iannbing commented on src/index.webmodeler.tsx
> +  [key: string]: any;
In the code below, it already shows that `props` has `labelCaption`, `linkTitle`, `renderType`, etc. Why not add them to the definition? Then we can get rid of the evil `any`

2019-09-12 08:35 UTC, iannbing commented on src/@typings/Widget.d.ts
> +  style?: React.CSSProperties;
Nice! I didn't know there's such type 👍

2019-09-12 08:38 UTC, iannbing commented on src/components/Link.tsx
> +  className?: string;
In `LinkButton`, `className` is not provided. So `className` will always be `undefined`.

2019-09-12 08:39 UTC, iannbing commented on src/components/LinkButton.tsx
> +      <Link
`Link` can accept `className`, but it is not provided. Maybe pass `props.buttonClass` to `<Link />`?

2019-09-12 08:44 UTC, iannbing commented on src/components/LinkButton.tsx
> +  style?: React.CSSProperties;
`style` is not used anywhere.

2019-09-12 08:45 UTC, iannbing commented on src/components/LinkButton.tsx
> +  className?: string;
`className` is not used.

2019-09-12 08:50 UTC, iannbing commented on src/components/LinkButton.tsx
> +  buttonStyle: BootstrapStyle;
`buttonStyle` sounds like inline styling, but it's not. How about `buttonType`?

2019-09-12 08:51 UTC, iannbing commented on src/components/LinkButton.tsx
> +        bootstrapStyle={props.buttonStyle}
`bootstrapStyle` also sounds like inline styling. Would it be better to name it something like `bootstrapButtonType`?

2019-09-12 08:57 UTC, iannbing commented on src/components/__tests__/LinkButton.test.tsx
> +      buttonstyle: 'info',
Should be camelcase here.

2019-09-12 08:57 UTC, iannbing commented on src/components/__tests__/LinkButton.test.tsx
> +      buttonstyle: '',
Should be camelcase here.

2019-09-12 09:09 UTC, iannbing commented on src/@typings/Widget.d.ts
> +  style?: React.CSSProperties;
But, `style` is a `string` here :-)

2019-09-12 09:10 UTC, iannbing commented on src/container/index.tsx
> +    style: parseStyle(params.style as string),
`params.style` is indeed a `string`, but `Widget.d.ts` says it's a `React.CSSProperties`. If you fix `Widget.d.ts`, you don't need to assert its type here.

2019-09-12 09:16 UTC, iannbing commented on src/container/index.tsx
> +const findElement = (parent: HTMLElement, targetClassName: string) => {
It is declared before being used. Could you move it to top?

2019-09-12 09:17 UTC, iannbing commented on src/container/index.tsx
> +  let target =
`const` is better since it's not re-assigned.

2019-09-12 09:18 UTC, iannbing commented on src/container/index.tsx
> +const render = (
This is also declared before being used.

2019-09-12 09:19 UTC, iannbing commented on src/container/index.tsx
> +const handleClick = (
This is also declared before being used.

2019-09-12 09:49 UTC, iannbing commented on src/container/index.tsx
> +  const text = !!(target as HTMLInputElement).value
```
const text = (target as HTMLInputElement).value || target.innerText;
```

2019-09-12 09:53 UTC, iannbing commented on src/container/index.tsx
> +  if (!!text) copyToClipboard(text);
Also show error when there's no text?

2019-09-12 10:15 UTC, iannbing commented on src/index.webmodeler.tsx
> +      return false;
Why does it have to return `false`?

2019-09-12 10:26 UTC, iannbing requested changes
In `widget.config.xml`, it doesn't read data from `package.json`. For example, `widgetFriendlyName` and `description`. Please read `webpack.dev.js` and `webpack.prod.js`.

2019-09-13 09:58 UTC, MeisamMahdian commented on src/index.tsx
> +  update(contextObject: mendix.lib.MxObject, callback: () => void) {
It's from Dojo. I can't remove it.

2019-09-13 12:24 UTC, MeisamMahdian commented on src/index.webmodeler.tsx
> +  [key: string]: any;
Done

2019-09-13 12:24 UTC, MeisamMahdian commented on src/@typings/Widget.d.ts
> +  style?: React.CSSProperties;
Fixed

2019-09-13 12:24 UTC, MeisamMahdian commented on src/components/Link.tsx
> +  className?: string;
Removed

2019-09-13 12:25 UTC, MeisamMahdian commented on src/components/LinkButton.tsx
> +      <Link
Removed

2019-09-13 12:25 UTC, MeisamMahdian commented on src/components/LinkButton.tsx
> +  style?: React.CSSProperties;
Removed

2019-09-13 12:25 UTC, MeisamMahdian commented on src/components/LinkButton.tsx
> +  buttonStyle: BootstrapStyle;
Done

2019-09-13 12:25 UTC, MeisamMahdian commented on src/components/LinkButton.tsx
> +        bootstrapStyle={props.buttonStyle}
Done

2019-09-13 12:26 UTC, MeisamMahdian commented on src/components/__tests__/LinkButton.test.tsx
> +      buttonstyle: '',
Fixed

2019-09-13 12:26 UTC, MeisamMahdian commented on src/components/LinkButton.tsx
> +  className?: string;
Removed

2019-09-13 12:26 UTC, MeisamMahdian commented on src/components/__tests__/LinkButton.test.tsx
> +      buttonstyle: 'info',
Fixed

2019-09-13 12:28 UTC, MeisamMahdian commented on src/container/index.tsx
> +    style: parseStyle(params.style as string),
Removed

2019-09-13 12:37 UTC, MeisamMahdian commented on src/container/index.tsx
> +const findElement = (parent: HTMLElement, targetClassName: string) => {
Done

2019-09-13 12:37 UTC, MeisamMahdian commented on src/container/index.tsx
> +  let target =
Fixed

2019-09-13 12:37 UTC, MeisamMahdian commented on src/container/index.tsx
> +const render = (
Done

2019-09-13 12:37 UTC, MeisamMahdian commented on src/container/index.tsx
> +const handleClick = (
Done

2019-09-13 12:38 UTC, MeisamMahdian commented on src/container/index.tsx
> +  const text = !!(target as HTMLInputElement).value
Done

2019-09-13 12:40 UTC, MeisamMahdian commented on src/container/index.tsx
> +  if (!!text) copyToClipboard(text);
I don't remember any environment that shows error for copying empty things. It shows error if it couldn't find the input text.

2019-09-13 12:44 UTC, MeisamMahdian commented on src/index.webmodeler.tsx
> +      return false;
It was an old habit of stopPropagation in DOM events. But here in React wrapper its irrelevant.

2019-09-13 12:53 UTC, MeisamMahdian commented
> In `widget.config.xml`, it doesn't read data from `package.json`. For example, `widgetFriendlyName` and `description`. Please read `webpack.dev.js` and `webpack.prod.js`.

Fixed that.

2019-09-18 07:39 UTC, iannbing approved these changes

2019-09-18 07:45 UTC, merged